name: Unzip file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Unzip the file
      run: |
        unzip path/to/your/file.zip -d path/to/unzipped/folder/
